#!/bin/bash
set -eu

msg() { printf "\033[1;34m$1\033[0m\n"; }
err() { printf "\33[31m[✘]\33[0m $1\033[0m\n" 1>&2; return 1; }
success() { printf "\33[32m[✔]\33[0m $1\033[0m\n"; }

msg "Bootstraping for Darwin..."

# Install basic dependencies
msg "Installing Homebrew ..."
if [[ $(uname -s) == Darwin ]]; then
  if [[ -x $(command -v brew) ]]; then
    # Homebrew is already installed, check for updates.
    brew upgrade && brew update
  else
    # Homebrew will install Xcode command line tools and brew.
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi
fi

msg "Installing dependencies..."
/opt/homebrew/bin/brew install bash \
             bash-completion \
             bat \
             btop \
             coreutils \
             direnv \
             findutils \
             fluxcd/tap/flux \
             fd \
             fzf \
             file \
             gawk \
             git \
             git-lfs \
             gnu-sed \
             gnu-tar \
             go-task \
             grep \
             jq \
             k9s \
             keychain \
             lnav \
             nvim \
             most \
             python3 \
             ripgrep \
             shellcheck \
             sops \
             starship \
             tmux \
             tree \
             wget \
             yazi \
             zip \
             zoxide

# Terminal

# Yabai 
brew install koekeishiya/formulae/yabai
yabai --start-service
brew install koekeishiya/formulae/skhd
