#!/bin/bash
set -eu

msg() { printf "\033[1;34m$1\033[0m\n"; }
err() { printf "\33[31m[✘]\33[0m $1\033[0m\n" 1>&2; return 1; }
success() { printf "\33[32m[✔]\33[0m $1\033[0m\n"; }

msg "Bootstraping for Debian..."

# Install basic dependencies
msg "Installing basic packages..."
export DEBIAN_FRONTEND=noninteractive

sudo apt -y update
# utilities
sudo apt -y install bash-completion \
                    bat \
                    btop \
                    build-essential \
                    curl \
                    direnv \
                    fd-find \
                    file \
                    fzf \
                    gcc \
                    git-lfs \
                    jq \
                    keychain \
                    less \
                    lnav \
                    man-db \
                    most \
                    nano \
                    net-tools \
                    nnn \
                    python-is-python3 \
                    python3 \
                    python3-pip \
                    python3-venv \
                    ripgrep \
                    shellcheck \
                    ssh \
                    tmux \
                    tree \
                    unzip \
                    wget

mkdir -p  "$HOME"/.local/bin/

# Install fd (https://github.com/sharkdp/fd)
ln -s $(which fdfind) ~/.local/bin/fd

# Instaling Starship (https://github.com/starship/starship)
curl -sS https://starship.rs/install.sh | sh -s -- -y

# Install Yazi (https://github.com/sxyazi/yazi)
curl -LO https://github.com/sxyazi/yazi/releases/latest/download/yazi-x86_64-unknown-linux-gnu.zip
unzip yazi-x86_64-unknown-linux-gnu.zip
rm -f yazi-x86_64-unknown-linux-gnu.zip yazi-x86_64-unknown-linux-gnu/README.md yazi-x86_64-unknown-linux-gnu/LICENSE
\cp -r yazi-x86_64-unknown-linux-gnu/* "$HOME"/.local/bin/
rm -rf yazi-x86_64-unknown-linux-gnu

# Install Zoxide (https://github.com/ajeetdsouza/zoxide)
curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash

# Install Bat (https://github.com/sharkdp/bat)
ln -sf /usr/bin/batcat "$HOME"/.local/bin/bat

# Install Nvim
curl -L https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.tar.gz | sudo tar zxf - -C /usr/local/ --strip-components=1
