#!/bin/bash
set -eu

msg() { printf "\033[1;34m$1\033[0m\n"; }
err() { printf "\33[31m[✘]\33[0m $1\033[0m\n" 1>&2; return 1; }
success() { printf "\33[32m[✔]\33[0m $1\033[0m\n"; }

msg "Bootstraping for Debian..."

# Install basic dependencies
msg "Installing basic packages..."
export DEBIAN_FRONTEND=noninteractive

sudo apt -y update
# utilities
sudo apt -y install bash-completion \
                    bat \
                    build-essential \
                    curl \
                    direnv \
                    gcc \
                    git-lfs \
                    htop \
                    jq \
                    keychain \
                    less \
                    lnav \
                    man-db \
                    most \
                    nano \
                    python-is-python3 \
                    python3 \
                    python3-pip \
                    python3-venv \
                    ripgrep \
                    shellcheck \
                    ssh \
                    tmux \
                    tree \
                    unzip \
                    wget

# Install Zoxide
curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash