return {
  arrows = {
    ArrowRight = "❯",
    ArrowLeft = "❮",
    -- ChevronRight = "",
    ChevronRight = ">",
    CurvedArrowRight = " ",
    DoubleArrowRight = "»",
    SmallArrowRight = "➜",
    Diamond = "<>",
  },
  ui = {
    Array = "󰅪",
		Branch = "",
		Boolean = "◩",
		Class = "󰠱",
		Color = "󰏘",
		Constant = "󰏿",
		Constructor = "",
		Enum = "",
		EnumMember = "",
		Event = "",
		Field = "󰆨",
		File = "󰈙",
		Folder = "󰉋",
		Function = "ƒ",
		Interface = "",
		Key = "",
		Keyword = "󰌋",
		Method = "󰆧",
		Module = "󰏗 ",
		Namespace = "󰅩",
		Number = "󰎠",
		Null = "󰟢",
		Object = "⦿",
		Operator = "+",
		Package = "󰏗",
		Property = "󰜢",
		Reference = "",
		Snippet = "",
		String = "𝓐",
		Struct = "󰙅",
		Text = "",
		TypeParameter = "󰆩",
		Unit = "",
		Value = "󰎠",
		Variable = "󰀫",
  },
  diagnostics = {
    Error = " ",
    Hint = " ",
    Information = " ",
    Question = " ",
    Warning = " ",
  },
  git = {
    Add = " ",
    Diff = " ",
    Ignore = " ",
    Mod = " ",
    Remove = " ",
    Rename = " ",
    Repo = " ",
  },
}
