#!/usr/bin/env bash
# Define environment variables to customize the command line interface


# Prevent Erase in Line (EL) to Right (\33[K) in the colored output of grep.
# Please read grep man page for further information.
export GREP_COLORS='ne'

# Use NVIM
if [[ -x /usr/local/bin/nvim ]] || command -v vim >/dev/null; then
    export EDITOR=nvim
fi

# Use most to display man pages using colors
if [[ -x /usr/bin/most ]] || command -v most >/dev/null; then
    export MANPAGER=most
fi

# Enable GCC colors (since GCC 4.8.0)
export GCC_COLORS=1

# Warn about dangerous environment
if [[ -s /etc/ld.so.preload ]]; then
    (tput bold && tput setaf 1) 2>/dev/null
    echo >&2 'Warning: /etc/ld.so.preload is present on this system!'
    tput sgr0 2>/dev/null
fi

if [[ -n "${LD_PRELOAD}" ]]; then
    (tput bold && tput setaf 1) 2>/dev/null
    echo >&2 'Warning: LD_PRELOAD is set!'
    tput sgr0 2>/dev/null
fi

if [[ -n "${LD_LIBRARY_PATH}" ]]; then
    (tput bold && tput setaf 1) 2>/dev/null
    echo >&2 'Warning: LD_LIBRARY_PATH is set!'
    tput sgr0 2>/dev/null
fi

# Load GNU coreutils into PATH
export PATH="$HOMEBREW_PREFIX/opt/coreutils/libexec/gnubin:$PATH"
export PATH="$HOMEBREW_PREFIX/opt/gnu-sed/libexec/gnubin:$PATH"
export PATH="$HOMEBREW_PREFIX/opt/grep/libexec/gnubin:$PATH"

export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:/usr/sbin/"

# Discover GNU coreutils man pages
export MANPATH="$HOMEBREW_PREFIX/opt/coreutils/libexec/man:$MANPATH"
export MANPATH="$HOMEBREW_PREFIX/opt/gnu-sed/libexec/man:$MANPATH"
export MANPATH="$HOMEBREW_PREFIX/opt/grep/libexec/man:$MANPATH"

if [[ $(uname) == 'Darwin' ]]; then
    # intell brew stuff is at /usr/local, silicon is at /opt
    export PATH="/usr/local/opt/coreutils/libexec/gnubin:/opt/local/bin:/opt/local/sbin:$PATH"
    export PATH="/usr/local/sbin:$HOME/.local/bin:/usr/local/opt/gettext/bin:$PATH"
    export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"
    export PATH="/opt/homebrew/opt/curl/bin:$PATH" # brew link --force doesn't work for this
    export PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:$PATH"
fi

# Shell completion
# ================
if [[ $(uname) == 'Darwin' ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
    source "$(brew --prefix)/etc/profile.d/bash_completion.sh"
    source "$(brew --prefix)/opt/git/etc/bash_completion.d/git-completion.bash"
    source "$(brew --prefix)/opt/git/etc/bash_completion.d/git-prompt.sh"
else
    [[ -r "/etc/bash_completion" ]] && source "/etc/bash_completion"
    [[ -r "/etc/bash_completion.d/git-prompt" ]] && source /etc/bash_completion.d/git-prompt
fi