#!/usr/bin/env bash

export HISTFILE="$HOME/.bash_history"
export HISTFILESIZE=10000
export HISTSIZE=10000

shopt -s histappend
export HISTCONTROL=ignoredups:erasedups:ignorespace

# store things in the history file as we go along
# also expand aliases
if ! echo "$PROMPT_COMMAND"  | grep -q history; then
  export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"
fi
