#!/bin/bash
set -eu

msg() { printf "\033[1;34m$1\033[0m\n"; }
err() {
  printf "\033[31m[✘]\033[0m $1\033[0m\n" 1>&2
  return 1
}
success() { printf "\033[32m[✔]\033[0m $1\033[0m\n"; }

is_darwin() {
  if [[ "$OSTYPE" == darwin* ]]; then
    return 0
  else
    return 1
  fi
}

is_debian() {
  if [ -f /etc/debian_version ]; then
    return 0
  else
    return 1
  fi
}

if is_debian; then curl -fsSL https://raw.githubusercontent.com/ra2f/dotfiles/main/install/bootstrap/debian | bash; fi
if is_darwin; then curl -fsSL https://raw.githubusercontent.com/ra2f/dotfiles/main/install/bootstrap/darwin | bash; fi

msg "Downloading dotfiles..."
cd "$(mktemp -d)"
wget https://codeload.github.com/ra2f/dotfiles/zip/refs/heads/main -O main.zip && unzip main.zip
cd dotfiles-main

msg "Copying configuration files ..."
mkdir -p "$HOME"/.config
cp -rf .config/bat .config/btop .config/direnv .config/ghostty .config/git .config/k9s .config/ssh .config/tmux .config/yazi .config/starship.toml "$HOME"/.config
cp -rf .local "$HOME"
cp -rf .bash* "$HOME"
cp -rf .profile "$HOME"
cp -rf .vimrc "$HOME"
cp -rf .curlrc "$HOME"

# rebuild bat's cache
bat cache --build