#!/bin/bash
set -e

dotdir=/tmp/dotfiles
homedir=$HOME

msg() { printf "\033[1;34m$1\033[0m\n"; }
err() { printf "\33[31m[✘]\33[0m $1\033[0m\n" 1>&2; return 1; }
success() { printf "\33[32m[✔]\33[0m $1\033[0m\n"; }

is_darwin() {
  if [[ "$OSTYPE" == darwin* ]]; then
    return 0
  else
    return 1
  fi
}

is_debian() {
  if [ -f /etc/debian_version ]; then
    return 0
  else
    return 1
  fi
}

# Remove any previous installation and install dotfiles
if [ -d "$dotdir" ]; then
  err "$dotdir alredy exist! Removing ..."
  rm -rf $dotdir
fi

if is_debian; then curl -fsSL https://raw.githubusercontent.com/ra2f/dotfiles/main/install/bootstrap/debian | bash; fi
if is_darwin; then curl -fsSL https://raw.githubusercontent.com/ra2f/dotfiles/main/install/bootstrap/darwin | bash; fi

msg "Downloading dotfiles..."
git clone git@github.com:ra2f/dotfiles.git $dotdir

msg "Copying configuration files ..."
cp -rf $dotdir/.config $homedir
cp -rf $dotdir/.local $homedir
cp -rf $dotdir/.bash* $homedir
cp -rf $dotdir/.hushlogin $homedir
